### ISSUE TITLE
Mark this repository as archived

### ISSUE THREAD

**Issue by bgamari** [haskell/array#3]
[GitLab](https://gitlab.haskell.org/ghc/packages/array) now serves as the official upstream.

**Comment by hvr** [comment]
@bgamari says who? :-)

If anything, I was intending to move it to https://gitlab.haskell.org/haskell/array instead but wasn't convinced yet whether  there's any benefit to keeping it here in the GitHub version of the haskell org; specifically I want the same level of CI convenience being able to test with the GHCs I package up I currently have on GitHub to justify a move to GitLab

**Comment by cartazio** [comment]
yeah, @hvr makes a good point ...

**Comment by cartazio** [comment]
what are CLC perms on gitlab, for that matter

**Comment by July541** [comment]
We are back to github.
